"""add_modulo_fabrica

Revision ID: f633c30b06da
Revises: a1b2c3d4e5f6
Create Date: 2026-04-01 20:53:52.870090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f633c30b06da'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SEQUENCE IF NOT EXISTS pedido_numero_seq")
    op.create_table('cliente',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('cpf_cnpj', sa.String(length=18), nullable=True),
    sa.Column('endereco', sa.String(length=300), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('cep', sa.String(length=9), nullable=True),
    sa.Column('observacoes', sa.String(length=500), nullable=True),
    sa.Column('ativo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cliente_user_id'), 'cliente', ['user_id'], unique=False)
    op.create_table('configuracao',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('chave', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.String(length=500), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'chave', name='uq_configuracao_user_chave')
    )
    op.create_index(op.f('ix_configuracao_user_id'), 'configuracao', ['user_id'], unique=False)
    op.create_table('pedido',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('numero', sa.Integer(), server_default=sa.text("nextval('pedido_numero_seq')"), nullable=False),
    sa.Column('cliente_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('rascunho', 'confirmado', 'enviado', 'cancelado', name='status_pedido_enum'), server_default='rascunho', nullable=False),
    sa.Column('observacoes', sa.String(length=500), nullable=True),
    sa.Column('valor_total', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_index(op.f('ix_pedido_cliente_id'), 'pedido', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_pedido_user_id'), 'pedido', ['user_id'], unique=False)
    op.create_table('email_log',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.Enum('confirmacao', 'consolidado', name='tipo_email_enum'), nullable=False),
    sa.Column('destinatario', sa.String(length=254), nullable=False),
    sa.Column('assunto', sa.String(length=300), nullable=False),
    sa.Column('status', sa.Enum('pendente', 'enviado', 'falha', name='status_email_enum'), server_default='pendente', nullable=False),
    sa.Column('erro', sa.String(length=500), nullable=True),
    sa.Column('pedido_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_log_user_id'), 'email_log', ['user_id'], unique=False)
    op.create_table('item_pedido',
    sa.Column('pedido_id', sa.Uuid(), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('valor_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_pedido_pedido_id'), 'item_pedido', ['pedido_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_pedido_pedido_id'), table_name='item_pedido')
    op.drop_table('item_pedido')
    op.drop_index(op.f('ix_email_log_user_id'), table_name='email_log')
    op.drop_table('email_log')
    op.drop_index(op.f('ix_pedido_user_id'), table_name='pedido')
    op.drop_index(op.f('ix_pedido_cliente_id'), table_name='pedido')
    op.drop_table('pedido')
    op.drop_index(op.f('ix_configuracao_user_id'), table_name='configuracao')
    op.drop_table('configuracao')
    op.drop_index(op.f('ix_cliente_user_id'), table_name='cliente')
    op.drop_table('cliente')
    op.execute("DROP SEQUENCE IF EXISTS pedido_numero_seq")
    # ### end Alembic commands ###
